### ISSUE TITLE
URL構造をリファクタ

### ISSUE THREAD

**Issue by regonn** [operando/OS-Event#9]
取得をRailsっぽく
/events/:site_name?range=today
みたいにしたい。

events#indexは一覧
events#showでidのかわりにatnd等のサイト名を入れることで、サイトだけが見える

さらに、クエリでsimple=trueや、どの範囲のデータを取ってくるのかを指定する

**Comment by operando** [comment]
RailsっぽいURL構造がなんかうまく解説してあるサイトがあれば、教えていただけるとありがたいです！
そもそもサーバサイドのURL構造なんてほとんど考えないで作ってしまうので。。。

ちなみに、API自体をもう少しSimpleにしてもいいかなーと思ってます。
多分需要があるのは、today、week、index(現event)くらいかと思ってます。
ちょいちょいhistoryとかも。
HerokuのLogも参考にして、不要なものはできるだけ削る形を取りたいと思います！

**Comment by regonn** [comment]
http://d.hatena.ne.jp/tkawa/20111031/p1#20111031f1
これかな？
あんまり、特別な事をしない限りmatchとかは使わずにresources or resourceでconfig/routesファイルを書いていきたい。
でindexとshowしか使わないんだったら, only: %i(index show)みたいに制限してあげてる。

**Comment by operando** [comment]
とりあえず/events/todayとか/events/weekとかにすればOK？？

**Comment by regonn** [comment]
:+1:

**Comment by shunsugai** [comment]
config/routes.rbを下みたいにしたいのだけど、
/events/eventというurlは不要で良いでしょうか？
/events/indexがその代わりになると思うので。

``` ruby
Rails.application.routes.draw do

  root 'events#event', defaults: { format: "json" }

  resources :events, only: [:index], defaults: { format: "json" } do
    get :simple,  on: :collection
    get :event,   on: :collection
    get :week,    on: :collection
    get :today,   on: :collection
    get :history, on: :collection
  end
end
```

```
$ bundle exec rake routes
        Prefix Verb URI Pattern               Controller#Action
          root GET  /                         events#event {:format=>"json"}
 simple_events GET  /events/simple(.:format)  events#simple {:format=>"json"}
  event_events GET  /events/event(.:format)   events#event {:format=>"json"}
   week_events GET  /events/week(.:format)    events#week {:format=>"json"}
  today_events GET  /events/today(.:format)   events#today {:format=>"json"}
history_events GET  /events/history(.:format) events#history {:format=>"json"}
        events GET  /events(.:format)         events#index {:format=>"json"}
```

**Comment by operando** [comment]
さすがっす:+1:
indexの件はそれでよいと思います！
